app:
  immoscout:
    auth:
      consumerKey: immobilen-telegram-search-botKey
      consumerSecret: yFksywwkTA7rPBSM
    url:
      requestToken: https://rest.immobilienscout24.de/restapi/security/oauth/request_token
      accessToken: https://rest.immobilienscout24.de/restapi/security/oauth/access_token
      confirmAccess: https://rest.immobilienscout24.de/restapi/security/oauth/confirm_access
      callback: https://immobilen-search-bot.herokuapp.com/api/immoscout
  telegram:
    botKey: 1156360777:AAHdQNF2Qvxd51cvjZqhAPQft2a3KKhZBrM